### ISSUE TITLE
Allow to override resources per environment

### ISSUE THREAD

**Issue by lkrzyzanek** [websitecd/operator#4]
Provide ability to override container resources and replicas

Example:
```yaml
envs:
  dev:
    namespace: ns-1
  prod:
    namespace: ns-3
    deployment:
      replicas: 5
      # init container
      init:
        # The standard k8s configuration
        resources:
          requests:
            cpu: 105m
            memory: 110Mi
          limits:
            cpu: 120m
            memory: 130Mi
      # httpd container
      httpd:
        resources:
          requests:
            cpu: 140m
            memory: 150Mi
          limits:
            cpu: 160m
            memory: 170Mi
      # api container
      api:
        resources:
          requests:
            cpu: 180m
            memory: 190Mi
          limits:
            cpu: 200m
            memory: 210Mi
```
